#!/bin/sh

### BEGIN INIT INFO
# Provides:          py-relay
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Author:            VladVons@gmail.com
# Short-Description: py-relay
# Description:       py-relay daemon
### END INIT INFO

# http://www.projectclearwater.org/using-start-stop-daemon-with-the-python-interpreter/

NAME="py-relay"
DESCR="Some description $NAME"
PIDFILE="/var/run/$NAME.pid"
USER="root"

# Read default configuration variable
ENABLED=1
SCRYPT="py-relay_Server.py"
WORKDIR="/usr/lib/$NAME"
ARGS=""
DEFAULT="/etc/default/$NAME"
if [ -r $DEFAULT ] ; then
  . $DEFAULT
fi
DAEMON="$WORKDIR/$SCRYPT"

. /lib/lsb/init-functions

case "$1" in
  start)
    if [ $ENABLED = 1 ]; then
      log_daemon_msg "Starting $NAME $DAEMON $ARGS"
      start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --chuid $USER --chdir $WORKDIR --exec $DAEMON -- $ARGS
      log_end_msg $?
    else
      log_daemon_msg "Disabled by $DEFAULT"
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $NAME "
    start-stop-daemon --stop --pidfile $PIDFILE --verbose --oknodo --retry=TERM/30/KILL/5
    log_end_msg $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    log_action_msg "Status $DAEMON"
    status_of_proc -p $PIDFILE "$DAEMON"
    ;;
  *)
    echo $DESCR
    log_action_msg  "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
