
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_11;
PyObject *const_int_pos_16;
PyObject *const_int_pos_24;
PyObject *const_int_pos_32;
PyObject *const_int_pos_60;
PyObject *const_int_pos_64;
PyObject *const_str_chr_40;
PyObject *const_str_chr_42;
PyObject *const_str_chr_44;
PyObject *const_str_chr_47;
PyObject *const_str_chr_58;
PyObject *const_int_pos_100;
PyObject *const_int_pos_128;
PyObject *const_int_pos_256;
PyObject *const_int_pos_512;
PyObject *const_str_plain_0;
PyObject *const_str_plain_E;
PyObject *const_str_plain_b;
PyObject *const_str_plain_d;
PyObject *const_str_plain_e;
PyObject *const_str_plain_i;
PyObject *const_str_plain_m;
PyObject *const_str_plain_o;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_v;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_int_pos_1024;
PyObject *const_int_pos_2048;
PyObject *const_int_pos_3600;
PyObject *const_str_plain_DB;
PyObject *const_str_plain_FS;
PyObject *const_str_plain_ID;
PyObject *const_str_plain_If;
PyObject *const_str_plain_db;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_int_pos_16384;
PyObject *const_int_pos_32768;
PyObject *const_int_pos_65536;
PyObject *const_int_pos_86400;
PyObject *const_str_plain_AES;
PyObject *const_str_plain_Add;
PyObject *const_str_plain_Api;
PyObject *const_str_plain_Arr;
PyObject *const_str_plain_Avg;
PyObject *const_str_plain_Dir;
PyObject *const_str_plain_Err;
PyObject *const_str_plain_Get;
PyObject *const_str_plain_Key;
PyObject *const_str_plain_Log;
PyObject *const_str_plain_Mac;
PyObject *const_str_plain_Msg;
PyObject *const_str_plain_Net;
PyObject *const_str_plain_Now;
PyObject *const_str_plain_Num;
PyObject *const_str_plain_Obj;
PyObject *const_str_plain_PY2;
PyObject *const_str_plain_Run;
PyObject *const_str_plain_SET;
PyObject *const_str_plain_SQL;
PyObject *const_str_plain_Set;
PyObject *const_str_plain_Str;
PyObject *const_str_plain_arg;
PyObject *const_str_plain_fmt;
PyObject *const_str_plain_get;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_min;
PyObject *const_str_plain_new;
PyObject *const_str_plain_now;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_res;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_BLOB;
PyObject *const_str_plain_Conn;
PyObject *const_str_plain_DATE;
PyObject *const_str_plain_Data;
PyObject *const_str_plain_Date;
PyObject *const_str_plain_Dict;
PyObject *const_str_plain_Diff;
PyObject *const_str_plain_Disk;
PyObject *const_str_plain_Dump;
PyObject *const_str_plain_ENUM;
PyObject *const_str_plain_Else;
PyObject *const_str_plain_Exec;
PyObject *const_str_plain_FLAG;
PyObject *const_str_plain_File;
PyObject *const_str_plain_Init;
PyObject *const_str_plain_Item;
PyObject *const_str_plain_JSON;
PyObject *const_str_plain_Keys;
PyObject *const_str_plain_LONG;
PyObject *const_str_plain_Line;
PyObject *const_str_plain_Load;
PyObject *const_str_plain_NULL;
PyObject *const_str_plain_None;
PyObject *const_str_plain_Path;
PyObject *const_str_plain_Post;
PyObject *const_str_plain_Repl;
PyObject *const_str_plain_Root;
PyObject *const_str_plain_Str1;
PyObject *const_str_plain_TAvg;
PyObject *const_str_plain_TIME;
PyObject *const_str_plain_TINY;
PyObject *const_str_plain_Then;
PyObject *const_str_plain_Time;
PyObject *const_str_plain_True;
PyObject *const_str_plain_Type;
PyObject *const_str_plain_YEAR;
PyObject *const_str_plain_aDef;
PyObject *const_str_plain_aDir;
PyObject *const_str_plain_aIdx;
PyObject *const_str_plain_aKey;
PyObject *const_str_plain_aMax;
PyObject *const_str_plain_aMin;
PyObject *const_str_plain_aMsg;
PyObject *const_str_plain_aObj;
PyObject *const_str_plain_aStr;
PyObject *const_str_plain_args;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_eth0;
PyObject *const_str_plain_exit;
PyObject *const_str_plain_info;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_json;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_list;
PyObject *const_str_plain_long;
PyObject *const_str_plain_mode;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_self;
PyObject *const_str_plain_site;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_walk;
PyObject *const_str_plain_Alias;
PyObject *const_str_plain_Check;
PyObject *const_str_plain_Clamp;
PyObject *const_str_plain_Class;
PyObject *const_str_plain_Clear;
PyObject *const_str_plain_Debug;
PyObject *const_str_plain_Depth;
PyObject *const_str_plain_Descr;
PyObject *const_str_plain_Error;
PyObject *const_str_plain_FLOAT;
PyObject *const_str_plain_False;
PyObject *const_str_plain_Files;
PyObject *const_str_plain_INT24;
PyObject *const_str_plain_Items;
PyObject *const_str_plain_Lines;
PyObject *const_str_plain_OnAvg;
PyObject *const_str_plain_Param;
PyObject *const_str_plain_Parse;
PyObject *const_str_plain_Print;
PyObject *const_str_plain_Range;
PyObject *const_str_plain_Ratio;
PyObject *const_str_plain_Round;
PyObject *const_str_plain_SHORT;
PyObject *const_str_plain_Start;
PyObject *const_str_plain_Sufix;
PyObject *const_str_plain_TExec;
PyObject *const_str_plain_Test1;
PyObject *const_str_plain_Value;
PyObject *const_str_plain_aData;
PyObject *const_str_plain_aFile;
PyObject *const_str_plain_aFunc;
PyObject *const_str_plain_aHost;
PyObject *const_str_plain_aName;
PyObject *const_str_plain_aPath;
PyObject *const_str_plain_aType;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_close;
PyObject *const_str_plain_dumps;
PyObject *const_str_plain_group;
PyObject *const_str_plain_index;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_loads;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_match;
PyObject *const_str_plain_prctl;
PyObject *const_str_plain_query;
PyObject *const_str_plain_range;
PyObject *const_str_plain_sleep;
PyObject *const_str_plain_split;
PyObject *const_str_plain_strip;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_value;
PyObject *const_str_plain_write;
PyObject *const_str_plain_Action;
PyObject *const_str_plain_Always;
PyObject *const_str_plain_BINARY;
PyObject *const_str_plain_CLIENT;
PyObject *const_str_plain_Caller;
PyObject *const_str_plain_Cipher;
PyObject *const_str_plain_Cursor;
PyObject *const_str_plain_DOUBLE;
PyObject *const_str_plain_DbDict;
PyObject *const_str_plain_Decode;
PyObject *const_str_plain_Enable;
PyObject *const_str_plain_Encode;
PyObject *const_str_plain_Finish;
PyObject *const_str_plain_GetAvg;
PyObject *const_str_plain_GetKey;
PyObject *const_str_plain_GetMac;
PyObject *const_str_plain_Macros;
PyObject *const_str_plain_Module;
PyObject *const_str_plain_Parent;
PyObject *const_str_plain_Prefix;
PyObject *const_str_plain_Result;
PyObject *const_str_plain_STRING;
PyObject *const_str_plain_Scrypt;
PyObject *const_str_plain_TCrypt;
PyObject *const_str_plain_TDbSQL;
PyObject *const_str_plain_TRange;
PyObject *const_str_plain_Update;
PyObject *const_str_plain_Uptime;
PyObject *const_str_plain__mysql;
PyObject *const_str_plain_aAlias;
PyObject *const_str_plain_aClass;
PyObject *const_str_plain_aDepth;
PyObject *const_str_plain_aParam;
PyObject *const_str_plain_aRange;
PyObject *const_str_plain_aValue;
PyObject *const_str_plain_append;
PyObject *const_str_plain_compat;
PyObject *const_str_plain_cursor;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_escape;
PyObject *const_str_plain_exists;
PyObject *const_str_plain_format;
PyObject *const_str_plain_isfile;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_object;
PyObject *const_str_plain_random;
PyObject *const_str_plain_update;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_Actions;
PyObject *const_str_plain_Classes;
PyObject *const_str_plain_Comment;
PyObject *const_str_plain_Connect;
PyObject *const_str_plain_CountIf;
PyObject *const_str_plain_DECIMAL;
PyObject *const_str_plain_Default;
PyObject *const_str_plain_DoStart;
PyObject *const_str_plain_GetAttr;
PyObject *const_str_plain_GetSize;
PyObject *const_str_plain_KeyFile;
PyObject *const_str_plain_KeyList;
PyObject *const_str_plain_Manager;
PyObject *const_str_plain_MySQLdb;
PyObject *const_str_plain_OnClass;
PyObject *const_str_plain_OnError;
PyObject *const_str_plain_OnParse;
PyObject *const_str_plain_OnRange;
PyObject *const_str_plain_OnValue;
PyObject *const_str_plain_Pattern;
PyObject *const_str_plain_RatioEx;
PyObject *const_str_plain_Section;
PyObject *const_str_plain_SetFile;
PyObject *const_str_plain_SetSize;
PyObject *const_str_plain_TDbDict;
PyObject *const_str_plain_TSensor;
PyObject *const_str_plain_Updated;
PyObject *const_str_plain_VARCHAR;
PyObject *const_str_plain_Version;
PyObject *const_str_plain_Warning;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain_aParent;
PyObject *const_str_plain_aPrefix;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_connect;
PyObject *const_str_plain_decrypt;
PyObject *const_str_plain_encrypt;
PyObject *const_str_plain_execute;
PyObject *const_str_plain_findall;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_isdigit;
PyObject *const_str_plain_literal;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_sqlite3;
PyObject *const_str_plain_unicode;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_plain_ClassRef;
PyObject *const_str_plain_DATETIME;
PyObject *const_str_plain_Delivery;
PyObject *const_str_plain_DoFinish;
PyObject *const_str_plain_ExtParam;
PyObject *const_str_plain_FileName;
PyObject *const_str_plain_FilePath;
PyObject *const_str_plain_GetClass;
PyObject *const_str_plain_Hardware;
PyObject *const_str_plain_Homepage;
PyObject *const_str_plain_LONGLONG;
PyObject *const_str_plain_LoadConf;
PyObject *const_str_plain_LoadFile;
PyObject *const_str_plain_LogLevel;
PyObject *const_str_plain_MODE_CBC;
PyObject *const_str_plain_MODE_CFB;
PyObject *const_str_plain_MODE_CTR;
PyObject *const_str_plain_MODE_ECB;
PyObject *const_str_plain_MODE_OFB;
PyObject *const_str_plain_MODE_PGP;
PyObject *const_str_plain_ParseDir;
PyObject *const_str_plain_ParseVar;
PyObject *const_str_plain_SetValue;
PyObject *const_str_plain_Software;
PyObject *const_str_plain_StrToSec;
PyObject *const_str_plain_TExecApi;
PyObject *const_str_plain_TManager;
PyObject *const_str_plain_TProtect;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain_datetime;
PyObject *const_str_plain_encoding;
PyObject *const_str_plain_exc_type;
PyObject *const_str_plain_fetchone;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_function;
PyObject *const_str_plain_messages;
PyObject *const_str_plain_property;
PyObject *const_str_plain_readline;
PyObject *const_str_plain_splitext;
PyObject *const_str_plain_strftime;
PyObject *const_str_plain_AddAction;
PyObject *const_str_plain_BlockAlgo;
PyObject *const_str_plain_ClassName;
PyObject *const_str_plain_ConvertTo;
PyObject *const_str_plain_CurResult;
PyObject *const_str_plain_DataError;
PyObject *const_str_plain_GetSerial;
PyObject *const_str_plain_GetUptime;
PyObject *const_str_plain_LONG_BLOB;
PyObject *const_str_plain_RoundPart;
PyObject *const_str_plain_SetMirror;
PyObject *const_str_plain_SetSource;
PyObject *const_str_plain_TDictCall;
PyObject *const_str_plain_TIMESTAMP;
PyObject *const_str_plain_TINY_BLOB;
PyObject *const_str_plain_TLoadConf;
PyObject *const_str_plain_TimeToSec;
PyObject *const_str_plain_Timestamp;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_exc_value;
PyObject *const_str_plain_fetch_row;
PyObject *const_str_plain_localtime;
PyObject *const_str_plain_readlines;
PyObject *const_tuple_str_dot_tuple;
PyObject *const_str_plain_BreakLabel;
PyObject *const_str_plain_CheckRange;
PyObject *const_str_plain_Conditions;
PyObject *const_str_plain_Connection;
PyObject *const_str_plain_EditorConf;
PyObject *const_str_plain_FIELD_TYPE;
PyObject *const_str_plain_FileExists;
PyObject *const_str_plain_GetVersion;
PyObject *const_str_plain_MySQLError;
PyObject *const_str_plain_NEWDECIMAL;
PyObject *const_str_plain_SetConsole;
PyObject *const_str_plain_TDictParam;
PyObject *const_str_plain_TDynImport;
PyObject *const_str_plain_VAR_STRING;
PyObject *const_str_plain__LoadClass;
PyObject *const_str_plain___author__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_block_size;
PyObject *const_str_plain_connection;
PyObject *const_str_plain_isinstance;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_CreateTable;
PyObject *const_str_plain_ExecSection;
PyObject *const_str_plain_GetCoreName;
PyObject *const_str_plain_GetDiskInfo;
PyObject *const_str_plain_GetHttpData;
PyObject *const_str_plain_GetInstance;
PyObject *const_str_plain_LoadKeyFile;
PyObject *const_str_plain_MEDIUM_BLOB;
PyObject *const_str_plain_PerCentSafe;
PyObject *const_str_plain_TEditorConf;
PyObject *const_str_plain_TExecResult;
PyObject *const_str_plain___delattr__;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___setattr__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_conversions;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_int_pos_2_tuple;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_str_plain_DateTimeType;
PyObject *const_str_plain_Date_or_None;
PyObject *const_str_plain_GetClassPath;
PyObject *const_str_plain_GetTreeAsStr;
PyObject *const_str_plain_LoadFromFile;
PyObject *const_str_plain_MODE_OPENPGP;
PyObject *const_str_plain_TDbDictMySQL;
PyObject *const_str_plain_TDeliveryArr;
PyObject *const_str_plain_TDictReplace;
PyObject *const_str_plain_TRANSACTIONS;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___revision__;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_store_result;
PyObject *const_str_plain_version_info;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_tuple_str_chr_44_tuple;
PyObject *const_tuple_str_chr_58_tuple;
PyObject *const_str_plain_AddDefPattern;
PyObject *const_str_plain_DatabaseError;
PyObject *const_str_plain_DateFromTicks;
PyObject *const_str_plain_InternalError;
PyObject *const_str_plain_MULTI_RESULTS;
PyObject *const_str_plain_StandardError;
PyObject *const_str_plain_StartTimeReal;
PyObject *const_str_plain_StartTimeVirt;
PyObject *const_str_plain_TDbDictSQLite;
PyObject *const_str_plain_TimeFromTicks;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__bytes_or_str;
PyObject *const_str_plain_exc_traceback;
PyObject *const_tuple_str_plain_s_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_CheckInterface;
PyObject *const_str_plain_IntegrityError;
PyObject *const_str_plain_InterfaceError;
PyObject *const_str_plain_RangeDecorator;
PyObject *const_str_plain_instancemethod;
PyObject *const_str_plain_string_literal;
PyObject *const_tuple_str_plain_FS_tuple;
PyObject *const_str_plain_TDeliverySQLite;
PyObject *const_tuple_str_plain_Log_tuple;
PyObject *const_str_plain_DateTime2literal;
PyObject *const_str_plain_DateTime_or_None;
PyObject *const_str_plain_MULTI_STATEMENTS;
PyObject *const_str_plain_OperationalError;
PyObject *const_str_plain_ProgrammingError;
PyObject *const_str_plain_SetStartTimeVirt;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_eth0_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain_DateTimeDeltaType;
PyObject *const_str_plain_LoadFromFileToStr;
PyObject *const_str_plain_NotSupportedError;
PyObject *const_str_plain_TimeDelta_or_None;
PyObject *const_tuple_str_plain_Start_tuple;
PyObject *const_str_plain_LoadFromFileToList;
PyObject *const_str_plain_SaveToFileFromList;
PyObject *const_str_plain_TimestampFromTicks;
PyObject *const_tuple_str_plain_Finish_tuple;
PyObject *const_tuple_str_plain_TDbSQL_tuple;
PyObject *const_tuple_str_plain_TDbDict_tuple;
PyObject *const_tuple_str_plain_ClassRef_tuple;
PyObject *const_str_plain_DateTimeDelta2literal;
PyObject *const_tuple_type_tuple_type_list_tuple;
PyObject *const_tuple_str_plain_Enable_true_tuple;
PyObject *const_tuple_str_plain_TEditorConf_tuple;
PyObject *const_tuple_str_plain_TDbDictSQLite_tuple;
PyObject *const_tuple_type_str_type_bytearray_tuple;
PyObject *const_tuple_str_plain_self_str_plain_SQL_tuple;
PyObject *const_list_str_plain_str_str_plain_unicode_list;
PyObject *const_tuple_str_plain_self_str_plain_aKey_tuple;
PyObject *const_tuple_str_plain_self_str_plain_aData_tuple;
PyObject *const_tuple_str_plain_self_str_plain_aFile_tuple;
PyObject *const_tuple_str_plain_self_str_plain_aName_tuple;
PyObject *const_str_digest_05cd2a7a408dc6619e97d739b1ced7db;
PyObject *const_str_digest_0be7fdd2b1a98685e612ed98cfe9d91f;
PyObject *const_str_digest_10c675d39d154a59cf6207a839b0661f;
PyObject *const_str_digest_121cccd956362e06ff46d801ff66ac46;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_27640573b8ce8850308523955531ea59;
PyObject *const_str_digest_2c46ee64b2d1a9ee629fb8b94f2a09ca;
PyObject *const_str_digest_301933b314eece8b5dc989888d4af40c;
PyObject *const_str_digest_3094a3153522c449dea0453cbf4eb75a;
PyObject *const_str_digest_3394dfb307e06a954b858974260bf51d;
PyObject *const_str_digest_391b5dc084c9caede4445b681a10e649;
PyObject *const_str_digest_3c2b5dd18916a4c86ef2a63bedc5a208;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_4afb6ac3c5c448817b7c4b2a044b9750;
PyObject *const_str_digest_512956f71065199b4656d61ab6cfc176;
PyObject *const_str_digest_51cafa63df0dba009586a31c534cfea1;
PyObject *const_str_digest_597c21d905f294da7964cde2c14a8ed1;
PyObject *const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1;
PyObject *const_str_digest_634ebcb288116ec16a2922e44740c97d;
PyObject *const_str_digest_6e1b9039a1198642c91d743e9550d006;
PyObject *const_str_digest_74ba315069266703540e145c62869e9e;
PyObject *const_str_digest_7bb187c562694df4ba2daaaf74308c83;
PyObject *const_str_digest_7d12dd513df7295340b2dd17a294a989;
PyObject *const_str_digest_819ab0780a8b33f0b631ef3a18023e51;
PyObject *const_str_digest_86574d8f15512ec9e1567cf1229e45d5;
PyObject *const_str_digest_94699d22af3f3c8e06bb4fcc526cb18f;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_9aab03a7c38b52b642ae4b5d35cda670;
PyObject *const_str_digest_9de9d760fdabf779aba9714e2d037b5a;
PyObject *const_str_digest_a9e53f924347f6fe3da0cfbd39c17c38;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_ade26fea59a84e8b725866efbaa8d71b;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_bf31fbca22bb3b1bbc45444e386bf3bf;
PyObject *const_str_digest_c769738ed6d4e413a546d14f7794acc6;
PyObject *const_str_digest_c8a872f25f0ec1e4843cc7cb49a7c386;
PyObject *const_str_digest_cfcfe764e764d5cda77bfdc5151807d1;
PyObject *const_str_digest_d24e34aca5cb8b1f44f63ad311518436;
PyObject *const_str_digest_e16b0126d837ce7ad3b9f1fbd3704965;
PyObject *const_str_digest_e46e74d31c85f83e29b4c3ce2454e2c5;
PyObject *const_str_digest_ec911207fdb78e7ed2e951a8c5294e18;
PyObject *const_str_digest_f4e70d26441bda5de2c5387519e51cc6;
PyObject *const_tuple_str_plain_self_str_plain_aAlias_tuple;
PyObject *const_tuple_str_plain_self_str_plain_aValue_tuple;
PyObject *const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple;
PyObject *const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple;
PyObject *const_tuple_str_plain_self_str_plain_aParent_tuple;
PyObject *const_list_str_plain_instancemethod_str_plain_function_list;
PyObject *const_tuple_str_plain_self_str_plain_aKey_str_plain_aValue_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyInt_FromLong( 0l );
    const_str_dot = UNSTREAM_CHAR( 46, 0 );
    const_int_neg_1 = PyInt_FromLong( -1l );
    const_int_pos_1 = PyInt_FromLong( 1l );
    const_int_pos_2 = PyInt_FromLong( 2l );
    const_int_pos_3 = PyInt_FromLong( 3l );
    const_int_pos_4 = PyInt_FromLong( 4l );
    const_int_pos_5 = PyInt_FromLong( 5l );
    const_int_pos_6 = PyInt_FromLong( 6l );
    const_int_pos_7 = PyInt_FromLong( 7l );
    const_int_pos_8 = PyInt_FromLong( 8l );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_10 = PyInt_FromLong( 10l );
    const_int_pos_11 = PyInt_FromLong( 11l );
    const_int_pos_16 = PyInt_FromLong( 16l );
    const_int_pos_24 = PyInt_FromLong( 24l );
    const_int_pos_32 = PyInt_FromLong( 32l );
    const_int_pos_60 = PyInt_FromLong( 60l );
    const_int_pos_64 = PyInt_FromLong( 64l );
    const_str_chr_40 = UNSTREAM_CHAR( 40, 0 );
    const_str_chr_42 = UNSTREAM_CHAR( 42, 0 );
    const_str_chr_44 = UNSTREAM_CHAR( 44, 0 );
    const_str_chr_47 = UNSTREAM_CHAR( 47, 0 );
    const_str_chr_58 = UNSTREAM_CHAR( 58, 0 );
    const_int_pos_100 = PyInt_FromLong( 100l );
    const_int_pos_128 = PyInt_FromLong( 128l );
    const_int_pos_256 = PyInt_FromLong( 256l );
    const_int_pos_512 = PyInt_FromLong( 512l );
    const_str_plain_0 = UNSTREAM_CHAR( 48, 0 );
    const_str_plain_E = UNSTREAM_CHAR( 69, 1 );
    const_str_plain_b = UNSTREAM_CHAR( 98, 1 );
    const_str_plain_d = UNSTREAM_CHAR( 100, 1 );
    const_str_plain_e = UNSTREAM_CHAR( 101, 1 );
    const_str_plain_i = UNSTREAM_CHAR( 105, 1 );
    const_str_plain_m = UNSTREAM_CHAR( 109, 1 );
    const_str_plain_o = UNSTREAM_CHAR( 111, 1 );
    const_str_plain_r = UNSTREAM_CHAR( 114, 1 );
    const_str_plain_s = UNSTREAM_CHAR( 115, 1 );
    const_str_plain_t = UNSTREAM_CHAR( 116, 1 );
    const_str_plain_v = UNSTREAM_CHAR( 118, 1 );
    const_str_plain_w = UNSTREAM_CHAR( 119, 1 );
    const_str_plain_x = UNSTREAM_CHAR( 120, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_int_pos_1024 = PyInt_FromLong( 1024l );
    const_int_pos_2048 = PyInt_FromLong( 2048l );
    const_int_pos_3600 = PyInt_FromLong( 3600l );
    const_str_plain_DB = UNSTREAM_STRING( &constant_bin[ 14994 ], 2, 1 );
    const_str_plain_FS = UNSTREAM_STRING( &constant_bin[ 20299 ], 2, 1 );
    const_str_plain_ID = UNSTREAM_STRING( &constant_bin[ 15242 ], 2, 1 );
    const_str_plain_If = UNSTREAM_STRING( &constant_bin[ 1771 ], 2, 1 );
    const_str_plain_db = UNSTREAM_STRING( &constant_bin[ 15998 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 297 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 40908 ], 2, 1 );
    const_str_plain_re = UNSTREAM_STRING( &constant_bin[ 31 ], 2, 1 );
    const_int_pos_16384 = PyInt_FromLong( 16384l );
    const_int_pos_32768 = PyInt_FromLong( 32768l );
    const_int_pos_65536 = PyInt_FromLong( 65536l );
    const_int_pos_86400 = PyInt_FromLong( 86400l );
    const_str_plain_AES = UNSTREAM_STRING( &constant_bin[ 2898 ], 3, 1 );
    const_str_plain_Add = UNSTREAM_STRING( &constant_bin[ 2337 ], 3, 1 );
    const_str_plain_Api = UNSTREAM_STRING( &constant_bin[ 41 ], 3, 1 );
    const_str_plain_Arr = UNSTREAM_STRING( &constant_bin[ 33964 ], 3, 1 );
    const_str_plain_Avg = UNSTREAM_STRING( &constant_bin[ 42238 ], 3, 1 );
    const_str_plain_Dir = UNSTREAM_STRING( &constant_bin[ 2586 ], 3, 1 );
    const_str_plain_Err = UNSTREAM_STRING( &constant_bin[ 10934 ], 3, 1 );
    const_str_plain_Get = UNSTREAM_STRING( &constant_bin[ 693 ], 3, 1 );
    const_str_plain_Key = UNSTREAM_STRING( &constant_bin[ 2386 ], 3, 1 );
    const_str_plain_Log = UNSTREAM_STRING( &constant_bin[ 18786 ], 3, 1 );
    const_str_plain_Mac = UNSTREAM_STRING( &constant_bin[ 21491 ], 3, 1 );
    const_str_plain_Msg = UNSTREAM_STRING( &constant_bin[ 42241 ], 3, 1 );
    const_str_plain_Net = UNSTREAM_STRING( &constant_bin[ 20826 ], 3, 1 );
    const_str_plain_Now = UNSTREAM_STRING( &constant_bin[ 15270 ], 3, 1 );
    const_str_plain_Num = UNSTREAM_STRING( &constant_bin[ 11467 ], 3, 1 );
    const_str_plain_Obj = UNSTREAM_STRING( &constant_bin[ 21659 ], 3, 1 );
    const_str_plain_PY2 = UNSTREAM_STRING( &constant_bin[ 42244 ], 3, 1 );
    const_str_plain_Run = UNSTREAM_STRING( &constant_bin[ 1990 ], 3, 1 );
    const_str_plain_SET = UNSTREAM_STRING( &constant_bin[ 15171 ], 3, 1 );
    const_str_plain_SQL = UNSTREAM_STRING( &constant_bin[ 14946 ], 3, 1 );
    const_str_plain_Set = UNSTREAM_STRING( &constant_bin[ 671 ], 3, 1 );
    const_str_plain_Str = UNSTREAM_STRING( &constant_bin[ 4385 ], 3, 1 );
    const_str_plain_arg = UNSTREAM_STRING( &constant_bin[ 11007 ], 3, 1 );
    const_str_plain_fmt = UNSTREAM_STRING( &constant_bin[ 18951 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 11128 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 482 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 2893 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 8167 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 11826 ], 3, 1 );
    const_str_plain_min = UNSTREAM_STRING( &constant_bin[ 4053 ], 3, 1 );
    const_str_plain_new = UNSTREAM_STRING( &constant_bin[ 5842 ], 3, 1 );
    const_str_plain_now = UNSTREAM_STRING( &constant_bin[ 1460 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 42247 ], 3, 1 );
    const_str_plain_res = UNSTREAM_STRING( &constant_bin[ 10957 ], 3, 1 );
    const_str_plain_str = UNSTREAM_STRING( &constant_bin[ 3371 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 7091 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 20953 ], 3, 1 );
    const_str_plain_BLOB = UNSTREAM_STRING( &constant_bin[ 42250 ], 4, 1 );
    const_str_plain_Conn = UNSTREAM_STRING( &constant_bin[ 21002 ], 4, 1 );
    const_str_plain_DATE = UNSTREAM_STRING( &constant_bin[ 15144 ], 4, 1 );
    const_str_plain_Data = UNSTREAM_STRING( &constant_bin[ 2443 ], 4, 1 );
    const_str_plain_Date = UNSTREAM_STRING( &constant_bin[ 22675 ], 4, 1 );
    const_str_plain_Dict = UNSTREAM_STRING( &constant_bin[ 2020 ], 4, 1 );
    const_str_plain_Diff = UNSTREAM_STRING( &constant_bin[ 42254 ], 4, 1 );
    const_str_plain_Disk = UNSTREAM_STRING( &constant_bin[ 365 ], 4, 1 );
    const_str_plain_Dump = UNSTREAM_STRING( &constant_bin[ 42258 ], 4, 1 );
    const_str_plain_ENUM = UNSTREAM_STRING( &constant_bin[ 42262 ], 4, 1 );
    const_str_plain_Else = UNSTREAM_STRING( &constant_bin[ 18178 ], 4, 1 );
    const_str_plain_Exec = UNSTREAM_STRING( &constant_bin[ 1707 ], 4, 1 );
    const_str_plain_FLAG = UNSTREAM_STRING( &constant_bin[ 31761 ], 4, 1 );
    const_str_plain_File = UNSTREAM_STRING( &constant_bin[ 2345 ], 4, 1 );
    const_str_plain_Init = UNSTREAM_STRING( &constant_bin[ 7997 ], 4, 1 );
    const_str_plain_Item = UNSTREAM_STRING( &constant_bin[ 15289 ], 4, 1 );
    const_str_plain_JSON = UNSTREAM_STRING( &constant_bin[ 42266 ], 4, 1 );
    const_str_plain_Keys = UNSTREAM_STRING( &constant_bin[ 2386 ], 4, 1 );
    const_str_plain_LONG = UNSTREAM_STRING( &constant_bin[ 31756 ], 4, 1 );
    const_str_plain_Line = UNSTREAM_STRING( &constant_bin[ 14057 ], 4, 1 );
    const_str_plain_Load = UNSTREAM_STRING( &constant_bin[ 2242 ], 4, 1 );
    const_str_plain_NULL = UNSTREAM_STRING( &constant_bin[ 22894 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING( &constant_bin[ 1312 ], 4, 1 );
    const_str_plain_Path = UNSTREAM_STRING( &constant_bin[ 13975 ], 4, 1 );
    const_str_plain_Post = UNSTREAM_STRING( &constant_bin[ 664 ], 4, 1 );
    const_str_plain_Repl = UNSTREAM_STRING( &constant_bin[ 2024 ], 4, 1 );
    const_str_plain_Root = UNSTREAM_STRING( &constant_bin[ 42270 ], 4, 1 );
    const_str_plain_Str1 = UNSTREAM_STRING( &constant_bin[ 42274 ], 4, 1 );
    const_str_plain_TAvg = UNSTREAM_STRING( &constant_bin[ 42278 ], 4, 1 );
    const_str_plain_TIME = UNSTREAM_STRING( &constant_bin[ 15207 ], 4, 1 );
    const_str_plain_TINY = UNSTREAM_STRING( &constant_bin[ 42282 ], 4, 1 );
    const_str_plain_Then = UNSTREAM_STRING( &constant_bin[ 18173 ], 4, 1 );
    const_str_plain_Time = UNSTREAM_STRING( &constant_bin[ 20448 ], 4, 1 );
    const_str_plain_True = UNSTREAM_STRING( &constant_bin[ 11958 ], 4, 1 );
    const_str_plain_Type = UNSTREAM_STRING( &constant_bin[ 4155 ], 4, 1 );
    const_str_plain_YEAR = UNSTREAM_STRING( &constant_bin[ 42286 ], 4, 1 );
    const_str_plain_aDef = UNSTREAM_STRING( &constant_bin[ 42290 ], 4, 1 );
    const_str_plain_aDir = UNSTREAM_STRING( &constant_bin[ 13971 ], 4, 1 );
    const_str_plain_aIdx = UNSTREAM_STRING( &constant_bin[ 42294 ], 4, 1 );
    const_str_plain_aKey = UNSTREAM_STRING( &constant_bin[ 42298 ], 4, 1 );
    const_str_plain_aMax = UNSTREAM_STRING( &constant_bin[ 42302 ], 4, 1 );
    const_str_plain_aMin = UNSTREAM_STRING( &constant_bin[ 42306 ], 4, 1 );
    const_str_plain_aMsg = UNSTREAM_STRING( &constant_bin[ 42310 ], 4, 1 );
    const_str_plain_aObj = UNSTREAM_STRING( &constant_bin[ 42314 ], 4, 1 );
    const_str_plain_aStr = UNSTREAM_STRING( &constant_bin[ 20144 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 26870 ], 4, 1 );
    const_str_plain_dict = UNSTREAM_STRING( &constant_bin[ 10996 ], 4, 1 );
    const_str_plain_eth0 = UNSTREAM_STRING( &constant_bin[ 42318 ], 4, 1 );
    const_str_plain_exit = UNSTREAM_STRING( &constant_bin[ 42322 ], 4, 1 );
    const_str_plain_info = UNSTREAM_STRING( &constant_bin[ 23179 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 12405 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 42326 ], 4, 1 );
    const_str_plain_json = UNSTREAM_STRING( &constant_bin[ 40662 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 4694 ], 4, 1 );
    const_str_plain_list = UNSTREAM_STRING( &constant_bin[ 14252 ], 4, 1 );
    const_str_plain_long = UNSTREAM_STRING( &constant_bin[ 3363 ], 4, 1 );
    const_str_plain_mode = UNSTREAM_STRING( &constant_bin[ 6056 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 4134 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 13113 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 42330 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 2156 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 32403 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 23878 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 22386 ], 4, 1 );
    const_str_plain_time = UNSTREAM_STRING( &constant_bin[ 1165 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 11821 ], 4, 1 );
    const_str_plain_walk = UNSTREAM_STRING( &constant_bin[ 42334 ], 4, 1 );
    const_str_plain_Alias = UNSTREAM_STRING( &constant_bin[ 633 ], 5, 1 );
    const_str_plain_Check = UNSTREAM_STRING( &constant_bin[ 658 ], 5, 1 );
    const_str_plain_Clamp = UNSTREAM_STRING( &constant_bin[ 42338 ], 5, 1 );
    const_str_plain_Class = UNSTREAM_STRING( &constant_bin[ 628 ], 5, 1 );
    const_str_plain_Clear = UNSTREAM_STRING( &constant_bin[ 19957 ], 5, 1 );
    const_str_plain_Debug = UNSTREAM_STRING( &constant_bin[ 42343 ], 5, 1 );
    const_str_plain_Depth = UNSTREAM_STRING( &constant_bin[ 1881 ], 5, 1 );
    const_str_plain_Descr = UNSTREAM_STRING( &constant_bin[ 277 ], 5, 1 );
    const_str_plain_Error = UNSTREAM_STRING( &constant_bin[ 10934 ], 5, 1 );
    const_str_plain_FLOAT = UNSTREAM_STRING( &constant_bin[ 42348 ], 5, 1 );
    const_str_plain_False = UNSTREAM_STRING( &constant_bin[ 11967 ], 5, 1 );
    const_str_plain_Files = UNSTREAM_STRING( &constant_bin[ 13940 ], 5, 1 );
    const_str_plain_INT24 = UNSTREAM_STRING( &constant_bin[ 42353 ], 5, 1 );
    const_str_plain_Items = UNSTREAM_STRING( &constant_bin[ 42358 ], 5, 1 );
    const_str_plain_Lines = UNSTREAM_STRING( &constant_bin[ 14227 ], 5, 1 );
    const_str_plain_OnAvg = UNSTREAM_STRING( &constant_bin[ 42363 ], 5, 1 );
    const_str_plain_Param = UNSTREAM_STRING( &constant_bin[ 684 ], 5, 1 );
    const_str_plain_Parse = UNSTREAM_STRING( &constant_bin[ 1720 ], 5, 1 );
    const_str_plain_Print = UNSTREAM_STRING( &constant_bin[ 480 ], 5, 1 );
    const_str_plain_Range = UNSTREAM_STRING( &constant_bin[ 1129 ], 5, 1 );
    const_str_plain_Ratio = UNSTREAM_STRING( &constant_bin[ 1415 ], 5, 1 );
    const_str_plain_Round = UNSTREAM_STRING( &constant_bin[ 1134 ], 5, 1 );
    const_str_plain_SHORT = UNSTREAM_STRING( &constant_bin[ 42368 ], 5, 1 );
    const_str_plain_Start = UNSTREAM_STRING( &constant_bin[ 1151 ], 5, 1 );
    const_str_plain_Sufix = UNSTREAM_STRING( &constant_bin[ 19316 ], 5, 1 );
    const_str_plain_TExec = UNSTREAM_STRING( &constant_bin[ 1715 ], 5, 1 );
    const_str_plain_Test1 = UNSTREAM_STRING( &constant_bin[ 473 ], 5, 1 );
    const_str_plain_Value = UNSTREAM_STRING( &constant_bin[ 643 ], 5, 1 );
    const_str_plain_aData = UNSTREAM_STRING( &constant_bin[ 20576 ], 5, 1 );
    const_str_plain_aFile = UNSTREAM_STRING( &constant_bin[ 20335 ], 5, 1 );
    const_str_plain_aFunc = UNSTREAM_STRING( &constant_bin[ 42373 ], 5, 1 );
    const_str_plain_aHost = UNSTREAM_STRING( &constant_bin[ 42378 ], 5, 1 );
    const_str_plain_aName = UNSTREAM_STRING( &constant_bin[ 42383 ], 5, 1 );
    const_str_plain_aPath = UNSTREAM_STRING( &constant_bin[ 42388 ], 5, 1 );
    const_str_plain_aType = UNSTREAM_STRING( &constant_bin[ 42393 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 6023 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 37213 ], 5, 1 );
    const_str_plain_dumps = UNSTREAM_STRING( &constant_bin[ 42398 ], 5, 1 );
    const_str_plain_group = UNSTREAM_STRING( &constant_bin[ 28468 ], 5, 1 );
    const_str_plain_index = UNSTREAM_STRING( &constant_bin[ 13014 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING( &constant_bin[ 21805 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 8077 ], 5, 1 );
    const_str_plain_loads = UNSTREAM_STRING( &constant_bin[ 42403 ], 5, 1 );
    const_str_plain_lower = UNSTREAM_STRING( &constant_bin[ 42408 ], 5, 1 );
    const_str_plain_match = UNSTREAM_STRING( &constant_bin[ 20114 ], 5, 1 );
    const_str_plain_prctl = UNSTREAM_STRING( &constant_bin[ 41422 ], 5, 1 );
    const_str_plain_query = UNSTREAM_STRING( &constant_bin[ 26476 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 19340 ], 5, 1 );
    const_str_plain_sleep = UNSTREAM_STRING( &constant_bin[ 42413 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 42418 ], 5, 1 );
    const_str_plain_strip = UNSTREAM_STRING( &constant_bin[ 14621 ], 5, 1 );
    const_str_plain_tuple = UNSTREAM_STRING( &constant_bin[ 10986 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 24450 ], 5, 1 );
    const_str_plain_write = UNSTREAM_STRING( &constant_bin[ 42423 ], 5, 1 );
    const_str_plain_Action = UNSTREAM_STRING( &constant_bin[ 736 ], 6, 1 );
    const_str_plain_Always = UNSTREAM_STRING( &constant_bin[ 42428 ], 6, 1 );
    const_str_plain_BINARY = UNSTREAM_STRING( &constant_bin[ 22617 ], 6, 1 );
    const_str_plain_CLIENT = UNSTREAM_STRING( &constant_bin[ 27107 ], 6, 1 );
    const_str_plain_Caller = UNSTREAM_STRING( &constant_bin[ 652 ], 6, 1 );
    const_str_plain_Cipher = UNSTREAM_STRING( &constant_bin[ 2878 ], 6, 1 );
    const_str_plain_Cursor = UNSTREAM_STRING( &constant_bin[ 25986 ], 6, 1 );
    const_str_plain_DOUBLE = UNSTREAM_STRING( &constant_bin[ 42434 ], 6, 1 );
    const_str_plain_DbDict = UNSTREAM_STRING( &constant_bin[ 14938 ], 6, 1 );
    const_str_plain_Decode = UNSTREAM_STRING( &constant_bin[ 42440 ], 6, 1 );
    const_str_plain_Enable = UNSTREAM_STRING( &constant_bin[ 42446 ], 6, 1 );
    const_str_plain_Encode = UNSTREAM_STRING( &constant_bin[ 42452 ], 6, 1 );
    const_str_plain_Finish = UNSTREAM_STRING( &constant_bin[ 21152 ], 6, 1 );
    const_str_plain_GetAvg = UNSTREAM_STRING( &constant_bin[ 42458 ], 6, 1 );
    const_str_plain_GetKey = UNSTREAM_STRING( &constant_bin[ 42464 ], 6, 1 );
    const_str_plain_GetMac = UNSTREAM_STRING( &constant_bin[ 21488 ], 6, 1 );
    const_str_plain_Macros = UNSTREAM_STRING( &constant_bin[ 40773 ], 6, 1 );
    const_str_plain_Module = UNSTREAM_STRING( &constant_bin[ 2195 ], 6, 1 );
    const_str_plain_Parent = UNSTREAM_STRING( &constant_bin[ 2185 ], 6, 1 );
    const_str_plain_Prefix = UNSTREAM_STRING( &constant_bin[ 15114 ], 6, 1 );
    const_str_plain_Result = UNSTREAM_STRING( &constant_bin[ 897 ], 6, 1 );
    const_str_plain_STRING = UNSTREAM_STRING( &constant_bin[ 23001 ], 6, 1 );
    const_str_plain_Scrypt = UNSTREAM_STRING( &constant_bin[ 18224 ], 6, 1 );
    const_str_plain_TCrypt = UNSTREAM_STRING( &constant_bin[ 42470 ], 6, 1 );
    const_str_plain_TDbSQL = UNSTREAM_STRING( &constant_bin[ 42476 ], 6, 1 );
    const_str_plain_TRange = UNSTREAM_STRING( &constant_bin[ 42482 ], 6, 1 );
    const_str_plain_Update = UNSTREAM_STRING( &constant_bin[ 14032 ], 6, 1 );
    const_str_plain_Uptime = UNSTREAM_STRING( &constant_bin[ 1163 ], 6, 1 );
    const_str_plain__mysql = UNSTREAM_STRING( &constant_bin[ 22310 ], 6, 1 );
    const_str_plain_aAlias = UNSTREAM_STRING( &constant_bin[ 42488 ], 6, 1 );
    const_str_plain_aClass = UNSTREAM_STRING( &constant_bin[ 18589 ], 6, 1 );
    const_str_plain_aDepth = UNSTREAM_STRING( &constant_bin[ 42494 ], 6, 1 );
    const_str_plain_aParam = UNSTREAM_STRING( &constant_bin[ 42500 ], 6, 1 );
    const_str_plain_aRange = UNSTREAM_STRING( &constant_bin[ 19381 ], 6, 1 );
    const_str_plain_aValue = UNSTREAM_STRING( &constant_bin[ 42506 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 42512 ], 6, 1 );
    const_str_plain_compat = UNSTREAM_STRING( &constant_bin[ 11878 ], 6, 1 );
    const_str_plain_cursor = UNSTREAM_STRING( &constant_bin[ 23117 ], 6, 1 );
    const_str_plain_encode = UNSTREAM_STRING( &constant_bin[ 12310 ], 6, 1 );
    const_str_plain_escape = UNSTREAM_STRING( &constant_bin[ 23139 ], 6, 1 );
    const_str_plain_exists = UNSTREAM_STRING( &constant_bin[ 2162 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 23517 ], 6, 1 );
    const_str_plain_isfile = UNSTREAM_STRING( &constant_bin[ 42518 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 26879 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 42524 ], 6, 1 );
    const_str_plain_object = UNSTREAM_STRING( &constant_bin[ 7135 ], 6, 1 );
    const_str_plain_random = UNSTREAM_STRING( &constant_bin[ 3390 ], 6, 1 );
    const_str_plain_update = UNSTREAM_STRING( &constant_bin[ 42530 ], 6, 1 );
    const_str_plain_xrange = UNSTREAM_STRING( &constant_bin[ 42536 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 42542 ], 9, 0 );
    const_str_plain_Actions = UNSTREAM_STRING( &constant_bin[ 42551 ], 7, 1 );
    const_str_plain_Classes = UNSTREAM_STRING( &constant_bin[ 2562 ], 7, 1 );
    const_str_plain_Comment = UNSTREAM_STRING( &constant_bin[ 14050 ], 7, 1 );
    const_str_plain_Connect = UNSTREAM_STRING( &constant_bin[ 22519 ], 7, 1 );
    const_str_plain_CountIf = UNSTREAM_STRING( &constant_bin[ 42558 ], 7, 1 );
    const_str_plain_DECIMAL = UNSTREAM_STRING( &constant_bin[ 42565 ], 7, 1 );
    const_str_plain_Default = UNSTREAM_STRING( &constant_bin[ 6154 ], 7, 1 );
    const_str_plain_DoStart = UNSTREAM_STRING( &constant_bin[ 1149 ], 7, 1 );
    const_str_plain_GetAttr = UNSTREAM_STRING( &constant_bin[ 42572 ], 7, 1 );
    const_str_plain_GetSize = UNSTREAM_STRING( &constant_bin[ 42579 ], 7, 1 );
    const_str_plain_KeyFile = UNSTREAM_STRING( &constant_bin[ 42586 ], 7, 1 );
    const_str_plain_KeyList = UNSTREAM_STRING( &constant_bin[ 42593 ], 7, 1 );
    const_str_plain_Manager = UNSTREAM_STRING( &constant_bin[ 2126 ], 7, 1 );
    const_str_plain_MySQLdb = UNSTREAM_STRING( &constant_bin[ 16259 ], 7, 1 );
    const_str_plain_OnClass = UNSTREAM_STRING( &constant_bin[ 626 ], 7, 1 );
    const_str_plain_OnError = UNSTREAM_STRING( &constant_bin[ 42600 ], 7, 1 );
    const_str_plain_OnParse = UNSTREAM_STRING( &constant_bin[ 42607 ], 7, 1 );
    const_str_plain_OnRange = UNSTREAM_STRING( &constant_bin[ 42614 ], 7, 1 );
    const_str_plain_OnValue = UNSTREAM_STRING( &constant_bin[ 40970 ], 7, 1 );
    const_str_plain_Pattern = UNSTREAM_STRING( &constant_bin[ 19352 ], 7, 1 );
    const_str_plain_RatioEx = UNSTREAM_STRING( &constant_bin[ 1435 ], 7, 1 );
    const_str_plain_Section = UNSTREAM_STRING( &constant_bin[ 1887 ], 7, 1 );
    const_str_plain_SetFile = UNSTREAM_STRING( &constant_bin[ 14166 ], 7, 1 );
    const_str_plain_SetSize = UNSTREAM_STRING( &constant_bin[ 42621 ], 7, 1 );
    const_str_plain_TDbDict = UNSTREAM_STRING( &constant_bin[ 42628 ], 7, 1 );
    const_str_plain_TSensor = UNSTREAM_STRING( &constant_bin[ 42635 ], 7, 1 );
    const_str_plain_Updated = UNSTREAM_STRING( &constant_bin[ 14426 ], 7, 1 );
    const_str_plain_VARCHAR = UNSTREAM_STRING( &constant_bin[ 16580 ], 7, 1 );
    const_str_plain_Version = UNSTREAM_STRING( &constant_bin[ 42642 ], 7, 1 );
    const_str_plain_Warning = UNSTREAM_STRING( &constant_bin[ 23035 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 42649 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 42656 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 42663 ], 7, 1 );
    const_str_plain_aParent = UNSTREAM_STRING( &constant_bin[ 42670 ], 7, 1 );
    const_str_plain_aPrefix = UNSTREAM_STRING( &constant_bin[ 42677 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 42684 ], 7, 1 );
    const_str_plain_connect = UNSTREAM_STRING( &constant_bin[ 15133 ], 7, 1 );
    const_str_plain_decrypt = UNSTREAM_STRING( &constant_bin[ 4985 ], 7, 1 );
    const_str_plain_encrypt = UNSTREAM_STRING( &constant_bin[ 2929 ], 7, 1 );
    const_str_plain_execute = UNSTREAM_STRING( &constant_bin[ 34691 ], 7, 1 );
    const_str_plain_findall = UNSTREAM_STRING( &constant_bin[ 42691 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 42698 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 42705 ], 7, 1 );
    const_str_plain_isdigit = UNSTREAM_STRING( &constant_bin[ 42712 ], 7, 1 );
    const_str_plain_literal = UNSTREAM_STRING( &constant_bin[ 12404 ], 7, 1 );
    const_str_plain_replace = UNSTREAM_STRING( &constant_bin[ 42719 ], 7, 1 );
    const_str_plain_sqlite3 = UNSTREAM_STRING( &constant_bin[ 42726 ], 7, 1 );
    const_str_plain_unicode = UNSTREAM_STRING( &constant_bin[ 12366 ], 7, 1 );
    const_tuple_false_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_plain_ClassRef = UNSTREAM_STRING( &constant_bin[ 1952 ], 8, 1 );
    const_str_plain_DATETIME = UNSTREAM_STRING( &constant_bin[ 42733 ], 8, 1 );
    const_str_plain_Delivery = UNSTREAM_STRING( &constant_bin[ 17113 ], 8, 1 );
    const_str_plain_DoFinish = UNSTREAM_STRING( &constant_bin[ 42741 ], 8, 1 );
    const_str_plain_ExtParam = UNSTREAM_STRING( &constant_bin[ 681 ], 8, 1 );
    const_str_plain_FileName = UNSTREAM_STRING( &constant_bin[ 20336 ], 8, 1 );
    const_str_plain_FilePath = UNSTREAM_STRING( &constant_bin[ 42749 ], 8, 1 );
    const_str_plain_GetClass = UNSTREAM_STRING( &constant_bin[ 21728 ], 8, 1 );
    const_str_plain_Hardware = UNSTREAM_STRING( &constant_bin[ 20098 ], 8, 1 );
    const_str_plain_Homepage = UNSTREAM_STRING( &constant_bin[ 42757 ], 8, 1 );
    const_str_plain_LONGLONG = UNSTREAM_STRING( &constant_bin[ 42765 ], 8, 1 );
    const_str_plain_LoadConf = UNSTREAM_STRING( &constant_bin[ 42773 ], 8, 1 );
    const_str_plain_LoadFile = UNSTREAM_STRING( &constant_bin[ 2352 ], 8, 1 );
    const_str_plain_LogLevel = UNSTREAM_STRING( &constant_bin[ 42781 ], 8, 1 );
    const_str_plain_MODE_CBC = UNSTREAM_STRING( &constant_bin[ 8932 ], 8, 1 );
    const_str_plain_MODE_CFB = UNSTREAM_STRING( &constant_bin[ 6934 ], 8, 1 );
    const_str_plain_MODE_CTR = UNSTREAM_STRING( &constant_bin[ 6322 ], 8, 1 );
    const_str_plain_MODE_ECB = UNSTREAM_STRING( &constant_bin[ 6166 ], 8, 1 );
    const_str_plain_MODE_OFB = UNSTREAM_STRING( &constant_bin[ 8948 ], 8, 1 );
    const_str_plain_MODE_PGP = UNSTREAM_STRING( &constant_bin[ 42789 ], 8, 1 );
    const_str_plain_ParseDir = UNSTREAM_STRING( &constant_bin[ 18471 ], 8, 1 );
    const_str_plain_ParseVar = UNSTREAM_STRING( &constant_bin[ 42797 ], 8, 1 );
    const_str_plain_SetValue = UNSTREAM_STRING( &constant_bin[ 671 ], 8, 1 );
    const_str_plain_Software = UNSTREAM_STRING( &constant_bin[ 42805 ], 8, 1 );
    const_str_plain_StrToSec = UNSTREAM_STRING( &constant_bin[ 42813 ], 8, 1 );
    const_str_plain_TExecApi = UNSTREAM_STRING( &constant_bin[ 42821 ], 8, 1 );
    const_str_plain_TManager = UNSTREAM_STRING( &constant_bin[ 42829 ], 8, 1 );
    const_str_plain_TProtect = UNSTREAM_STRING( &constant_bin[ 42837 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 42845 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 42853 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 42861 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 101 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 42869 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 42877 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 42885 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 42893 ], 8, 1 );
    const_str_plain_datetime = UNSTREAM_STRING( &constant_bin[ 39922 ], 8, 1 );
    const_str_plain_encoding = UNSTREAM_STRING( &constant_bin[ 11746 ], 8, 1 );
    const_str_plain_exc_type = UNSTREAM_STRING( &constant_bin[ 42901 ], 8, 1 );
    const_str_plain_fetchone = UNSTREAM_STRING( &constant_bin[ 42909 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 42917 ], 8, 1 );
    const_str_plain_function = UNSTREAM_STRING( &constant_bin[ 3107 ], 8, 1 );
    const_str_plain_messages = UNSTREAM_STRING( &constant_bin[ 42925 ], 8, 1 );
    const_str_plain_property = UNSTREAM_STRING( &constant_bin[ 42933 ], 8, 1 );
    const_str_plain_readline = UNSTREAM_STRING( &constant_bin[ 42941 ], 8, 1 );
    const_str_plain_splitext = UNSTREAM_STRING( &constant_bin[ 42949 ], 8, 1 );
    const_str_plain_strftime = UNSTREAM_STRING( &constant_bin[ 42957 ], 8, 1 );
    const_str_plain_AddAction = UNSTREAM_STRING( &constant_bin[ 42965 ], 9, 1 );
    const_str_plain_BlockAlgo = UNSTREAM_STRING( &constant_bin[ 42974 ], 9, 1 );
    const_str_plain_ClassName = UNSTREAM_STRING( &constant_bin[ 2269 ], 9, 1 );
    const_str_plain_ConvertTo = UNSTREAM_STRING( &constant_bin[ 42983 ], 9, 1 );
    const_str_plain_CurResult = UNSTREAM_STRING( &constant_bin[ 42992 ], 9, 1 );
    const_str_plain_DataError = UNSTREAM_STRING( &constant_bin[ 22766 ], 9, 1 );
    const_str_plain_GetSerial = UNSTREAM_STRING( &constant_bin[ 19991 ], 9, 1 );
    const_str_plain_GetUptime = UNSTREAM_STRING( &constant_bin[ 1160 ], 9, 1 );
    const_str_plain_LONG_BLOB = UNSTREAM_STRING( &constant_bin[ 43001 ], 9, 1 );
    const_str_plain_RoundPart = UNSTREAM_STRING( &constant_bin[ 43010 ], 9, 1 );
    const_str_plain_SetMirror = UNSTREAM_STRING( &constant_bin[ 43019 ], 9, 1 );
    const_str_plain_SetSource = UNSTREAM_STRING( &constant_bin[ 43028 ], 9, 1 );
    const_str_plain_TDictCall = UNSTREAM_STRING( &constant_bin[ 43037 ], 9, 1 );
    const_str_plain_TIMESTAMP = UNSTREAM_STRING( &constant_bin[ 15207 ], 9, 1 );
    const_str_plain_TINY_BLOB = UNSTREAM_STRING( &constant_bin[ 43046 ], 9, 1 );
    const_str_plain_TLoadConf = UNSTREAM_STRING( &constant_bin[ 43055 ], 9, 1 );
    const_str_plain_TimeToSec = UNSTREAM_STRING( &constant_bin[ 43064 ], 9, 1 );
    const_str_plain_Timestamp = UNSTREAM_STRING( &constant_bin[ 22693 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 43073 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING( &constant_bin[ 43082 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 43091 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 43100 ], 9, 1 );
    const_str_plain_exc_value = UNSTREAM_STRING( &constant_bin[ 43109 ], 9, 1 );
    const_str_plain_fetch_row = UNSTREAM_STRING( &constant_bin[ 37191 ], 9, 1 );
    const_str_plain_localtime = UNSTREAM_STRING( &constant_bin[ 43118 ], 9, 1 );
    const_str_plain_readlines = UNSTREAM_STRING( &constant_bin[ 42941 ], 9, 1 );
    const_tuple_str_dot_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_dot_tuple, 0, const_str_dot ); Py_INCREF( const_str_dot );
    const_str_plain_BreakLabel = UNSTREAM_STRING( &constant_bin[ 43127 ], 10, 1 );
    const_str_plain_CheckRange = UNSTREAM_STRING( &constant_bin[ 22121 ], 10, 1 );
    const_str_plain_Conditions = UNSTREAM_STRING( &constant_bin[ 1420 ], 10, 1 );
    const_str_plain_Connection = UNSTREAM_STRING( &constant_bin[ 22519 ], 10, 1 );
    const_str_plain_EditorConf = UNSTREAM_STRING( &constant_bin[ 43137 ], 10, 1 );
    const_str_plain_FIELD_TYPE = UNSTREAM_STRING( &constant_bin[ 22808 ], 10, 1 );
    const_str_plain_FileExists = UNSTREAM_STRING( &constant_bin[ 43147 ], 10, 1 );
    const_str_plain_GetVersion = UNSTREAM_STRING( &constant_bin[ 43157 ], 10, 1 );
    const_str_plain_MySQLError = UNSTREAM_STRING( &constant_bin[ 22879 ], 10, 1 );
    const_str_plain_NEWDECIMAL = UNSTREAM_STRING( &constant_bin[ 43167 ], 10, 1 );
    const_str_plain_SetConsole = UNSTREAM_STRING( &constant_bin[ 43177 ], 10, 1 );
    const_str_plain_TDictParam = UNSTREAM_STRING( &constant_bin[ 43187 ], 10, 1 );
    const_str_plain_TDynImport = UNSTREAM_STRING( &constant_bin[ 18451 ], 10, 1 );
    const_str_plain_VAR_STRING = UNSTREAM_STRING( &constant_bin[ 43197 ], 10, 1 );
    const_str_plain__LoadClass = UNSTREAM_STRING( &constant_bin[ 2241 ], 10, 1 );
    const_str_plain___author__ = UNSTREAM_STRING( &constant_bin[ 43207 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 43217 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 43227 ], 10, 1 );
    const_str_plain_block_size = UNSTREAM_STRING( &constant_bin[ 6374 ], 10, 1 );
    const_str_plain_connection = UNSTREAM_STRING( &constant_bin[ 22507 ], 10, 1 );
    const_str_plain_isinstance = UNSTREAM_STRING( &constant_bin[ 11992 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 43237 ], 10, 1 );
    const_str_plain_CreateTable = UNSTREAM_STRING( &constant_bin[ 43247 ], 11, 1 );
    const_str_plain_ExecSection = UNSTREAM_STRING( &constant_bin[ 18193 ], 11, 1 );
    const_str_plain_GetCoreName = UNSTREAM_STRING( &constant_bin[ 43258 ], 11, 1 );
    const_str_plain_GetDiskInfo = UNSTREAM_STRING( &constant_bin[ 43269 ], 11, 1 );
    const_str_plain_GetHttpData = UNSTREAM_STRING( &constant_bin[ 43280 ], 11, 1 );
    const_str_plain_GetInstance = UNSTREAM_STRING( &constant_bin[ 18505 ], 11, 1 );
    const_str_plain_LoadKeyFile = UNSTREAM_STRING( &constant_bin[ 43291 ], 11, 1 );
    const_str_plain_MEDIUM_BLOB = UNSTREAM_STRING( &constant_bin[ 43302 ], 11, 1 );
    const_str_plain_PerCentSafe = UNSTREAM_STRING( &constant_bin[ 43313 ], 11, 1 );
    const_str_plain_TEditorConf = UNSTREAM_STRING( &constant_bin[ 43324 ], 11, 1 );
    const_str_plain_TExecResult = UNSTREAM_STRING( &constant_bin[ 43335 ], 11, 1 );
    const_str_plain___delattr__ = UNSTREAM_STRING( &constant_bin[ 43346 ], 11, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 43357 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 5646 ], 11, 1 );
    const_str_plain___setattr__ = UNSTREAM_STRING( &constant_bin[ 43368 ], 11, 1 );
    const_str_plain___version__ = UNSTREAM_STRING( &constant_bin[ 43379 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 43390 ], 11, 1 );
    const_str_plain_conversions = UNSTREAM_STRING( &constant_bin[ 26890 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_pos_2_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_tuple, 0, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    const_tuple_str_empty_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_empty_tuple, 0, const_str_empty ); Py_INCREF( const_str_empty );
    const_str_plain_DateTimeType = UNSTREAM_STRING( &constant_bin[ 43401 ], 12, 1 );
    const_str_plain_Date_or_None = UNSTREAM_STRING( &constant_bin[ 43413 ], 12, 1 );
    const_str_plain_GetClassPath = UNSTREAM_STRING( &constant_bin[ 43425 ], 12, 1 );
    const_str_plain_GetTreeAsStr = UNSTREAM_STRING( &constant_bin[ 43437 ], 12, 1 );
    const_str_plain_LoadFromFile = UNSTREAM_STRING( &constant_bin[ 43449 ], 12, 1 );
    const_str_plain_MODE_OPENPGP = UNSTREAM_STRING( &constant_bin[ 6347 ], 12, 1 );
    const_str_plain_TDbDictMySQL = UNSTREAM_STRING( &constant_bin[ 43461 ], 12, 1 );
    const_str_plain_TDeliveryArr = UNSTREAM_STRING( &constant_bin[ 43473 ], 12, 1 );
    const_str_plain_TDictReplace = UNSTREAM_STRING( &constant_bin[ 43485 ], 12, 1 );
    const_str_plain_TRANSACTIONS = UNSTREAM_STRING( &constant_bin[ 43497 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 43509 ], 12, 1 );
    const_str_plain___compiled__ = UNSTREAM_STRING( &constant_bin[ 43521 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 43533 ], 12, 1 );
    const_str_plain___revision__ = UNSTREAM_STRING( &constant_bin[ 5632 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 43545 ], 12, 1 );
    const_str_plain_store_result = UNSTREAM_STRING( &constant_bin[ 36841 ], 12, 1 );
    const_str_plain_version_info = UNSTREAM_STRING( &constant_bin[ 23239 ], 12, 1 );
    const_tuple_str_chr_42_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_42_tuple, 0, const_str_chr_42 ); Py_INCREF( const_str_chr_42 );
    const_tuple_str_chr_44_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_44_tuple, 0, const_str_chr_44 ); Py_INCREF( const_str_chr_44 );
    const_tuple_str_chr_58_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_58_tuple, 0, const_str_chr_58 ); Py_INCREF( const_str_chr_58 );
    const_str_plain_AddDefPattern = UNSTREAM_STRING( &constant_bin[ 43557 ], 13, 1 );
    const_str_plain_DatabaseError = UNSTREAM_STRING( &constant_bin[ 22780 ], 13, 1 );
    const_str_plain_DateFromTicks = UNSTREAM_STRING( &constant_bin[ 22707 ], 13, 1 );
    const_str_plain_InternalError = UNSTREAM_STRING( &constant_bin[ 22861 ], 13, 1 );
    const_str_plain_MULTI_RESULTS = UNSTREAM_STRING( &constant_bin[ 43570 ], 13, 1 );
    const_str_plain_StandardError = UNSTREAM_STRING( &constant_bin[ 43583 ], 13, 1 );
    const_str_plain_StartTimeReal = UNSTREAM_STRING( &constant_bin[ 43596 ], 13, 1 );
    const_str_plain_StartTimeVirt = UNSTREAM_STRING( &constant_bin[ 43609 ], 13, 1 );
    const_str_plain_TDbDictSQLite = UNSTREAM_STRING( &constant_bin[ 43622 ], 13, 1 );
    const_str_plain_TimeFromTicks = UNSTREAM_STRING( &constant_bin[ 22725 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 43635 ], 13, 1 );
    const_str_plain__bytes_or_str = UNSTREAM_STRING( &constant_bin[ 26961 ], 13, 1 );
    const_str_plain_exc_traceback = UNSTREAM_STRING( &constant_bin[ 43648 ], 13, 1 );
    const_tuple_str_plain_s_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_s_tuple, 0, const_str_plain_s ); Py_INCREF( const_str_plain_s );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain_CheckInterface = UNSTREAM_STRING( &constant_bin[ 43661 ], 14, 1 );
    const_str_plain_IntegrityError = UNSTREAM_STRING( &constant_bin[ 22823 ], 14, 1 );
    const_str_plain_InterfaceError = UNSTREAM_STRING( &constant_bin[ 22842 ], 14, 1 );
    const_str_plain_RangeDecorator = UNSTREAM_STRING( &constant_bin[ 43675 ], 14, 1 );
    const_str_plain_instancemethod = UNSTREAM_STRING( &constant_bin[ 43689 ], 14, 1 );
    const_str_plain_string_literal = UNSTREAM_STRING( &constant_bin[ 23203 ], 14, 1 );
    const_tuple_str_plain_FS_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_FS_tuple, 0, const_str_plain_FS ); Py_INCREF( const_str_plain_FS );
    const_str_plain_TDeliverySQLite = UNSTREAM_STRING( &constant_bin[ 43703 ], 15, 1 );
    const_tuple_str_plain_Log_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Log_tuple, 0, const_str_plain_Log ); Py_INCREF( const_str_plain_Log );
    const_str_plain_DateTime2literal = UNSTREAM_STRING( &constant_bin[ 43718 ], 16, 1 );
    const_str_plain_DateTime_or_None = UNSTREAM_STRING( &constant_bin[ 43734 ], 16, 1 );
    const_str_plain_MULTI_STATEMENTS = UNSTREAM_STRING( &constant_bin[ 43750 ], 16, 1 );
    const_str_plain_OperationalError = UNSTREAM_STRING( &constant_bin[ 22949 ], 16, 1 );
    const_str_plain_ProgrammingError = UNSTREAM_STRING( &constant_bin[ 22970 ], 16, 1 );
    const_str_plain_SetStartTimeVirt = UNSTREAM_STRING( &constant_bin[ 43766 ], 16, 1 );
    const_tuple_none_none_none_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 2, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_plain_eth0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_eth0_tuple, 0, const_str_plain_eth0 ); Py_INCREF( const_str_plain_eth0 );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain_DateTimeDeltaType = UNSTREAM_STRING( &constant_bin[ 43782 ], 17, 1 );
    const_str_plain_LoadFromFileToStr = UNSTREAM_STRING( &constant_bin[ 43799 ], 17, 1 );
    const_str_plain_NotSupportedError = UNSTREAM_STRING( &constant_bin[ 22914 ], 17, 1 );
    const_str_plain_TimeDelta_or_None = UNSTREAM_STRING( &constant_bin[ 43816 ], 17, 1 );
    const_tuple_str_plain_Start_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Start_tuple, 0, const_str_plain_Start ); Py_INCREF( const_str_plain_Start );
    const_str_plain_LoadFromFileToList = UNSTREAM_STRING( &constant_bin[ 43833 ], 18, 1 );
    const_str_plain_SaveToFileFromList = UNSTREAM_STRING( &constant_bin[ 43851 ], 18, 1 );
    const_str_plain_TimestampFromTicks = UNSTREAM_STRING( &constant_bin[ 22743 ], 18, 1 );
    const_tuple_str_plain_Finish_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Finish_tuple, 0, const_str_plain_Finish ); Py_INCREF( const_str_plain_Finish );
    const_tuple_str_plain_TDbSQL_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_TDbSQL_tuple, 0, const_str_plain_TDbSQL ); Py_INCREF( const_str_plain_TDbSQL );
    const_tuple_str_plain_TDbDict_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_TDbDict_tuple, 0, const_str_plain_TDbDict ); Py_INCREF( const_str_plain_TDbDict );
    const_tuple_str_plain_ClassRef_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_ClassRef_tuple, 0, const_str_plain_ClassRef ); Py_INCREF( const_str_plain_ClassRef );
    const_str_plain_DateTimeDelta2literal = UNSTREAM_STRING( &constant_bin[ 43869 ], 21, 1 );
    const_tuple_type_tuple_type_list_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_type_tuple_type_list_tuple, 0, (PyObject *)&PyTuple_Type ); Py_INCREF( (PyObject *)&PyTuple_Type );
    PyTuple_SET_ITEM( const_tuple_type_tuple_type_list_tuple, 1, (PyObject *)&PyList_Type ); Py_INCREF( (PyObject *)&PyList_Type );
    const_tuple_str_plain_Enable_true_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Enable_true_tuple, 0, const_str_plain_Enable ); Py_INCREF( const_str_plain_Enable );
    PyTuple_SET_ITEM( const_tuple_str_plain_Enable_true_tuple, 1, Py_True ); Py_INCREF( Py_True );
    const_tuple_str_plain_TEditorConf_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_TEditorConf_tuple, 0, const_str_plain_TEditorConf ); Py_INCREF( const_str_plain_TEditorConf );
    const_tuple_str_plain_TDbDictSQLite_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_TDbDictSQLite_tuple, 0, const_str_plain_TDbDictSQLite ); Py_INCREF( const_str_plain_TDbDictSQLite );
    const_tuple_type_str_type_bytearray_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_type_str_type_bytearray_tuple, 0, (PyObject *)&PyString_Type ); Py_INCREF( (PyObject *)&PyString_Type );
    PyTuple_SET_ITEM( const_tuple_type_str_type_bytearray_tuple, 1, (PyObject *)&PyByteArray_Type ); Py_INCREF( (PyObject *)&PyByteArray_Type );
    const_tuple_str_plain_self_str_plain_SQL_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_SQL_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_SQL_tuple, 1, const_str_plain_SQL ); Py_INCREF( const_str_plain_SQL );
    const_list_str_plain_str_str_plain_unicode_list = PyList_New( 2 );
    PyList_SET_ITEM( const_list_str_plain_str_str_plain_unicode_list, 0, const_str_plain_str ); Py_INCREF( const_str_plain_str );
    PyList_SET_ITEM( const_list_str_plain_str_str_plain_unicode_list, 1, const_str_plain_unicode ); Py_INCREF( const_str_plain_unicode );
    const_tuple_str_plain_self_str_plain_aKey_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aKey_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aKey_tuple, 1, const_str_plain_aKey ); Py_INCREF( const_str_plain_aKey );
    const_tuple_str_plain_self_str_plain_aData_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aData_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aData_tuple, 1, const_str_plain_aData ); Py_INCREF( const_str_plain_aData );
    const_tuple_str_plain_self_str_plain_aFile_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aFile_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aFile_tuple, 1, const_str_plain_aFile ); Py_INCREF( const_str_plain_aFile );
    const_tuple_str_plain_self_str_plain_aName_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aName_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aName_tuple, 1, const_str_plain_aName ); Py_INCREF( const_str_plain_aName );
    const_str_digest_05cd2a7a408dc6619e97d739b1ced7db = UNSTREAM_STRING( &constant_bin[ 31732 ], 17, 0 );
    const_str_digest_0be7fdd2b1a98685e612ed98cfe9d91f = UNSTREAM_STRING( &constant_bin[ 43890 ], 174, 0 );
    const_str_digest_10c675d39d154a59cf6207a839b0661f = UNSTREAM_STRING( &constant_bin[ 44064 ], 4, 0 );
    const_str_digest_121cccd956362e06ff46d801ff66ac46 = UNSTREAM_STRING( &constant_bin[ 44068 ], 174, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 679 ], 2, 0 );
    const_str_digest_27640573b8ce8850308523955531ea59 = UNSTREAM_STRING( &constant_bin[ 44242 ], 174, 0 );
    const_str_digest_2c46ee64b2d1a9ee629fb8b94f2a09ca = UNSTREAM_STRING( &constant_bin[ 23575 ], 18, 0 );
    const_str_digest_301933b314eece8b5dc989888d4af40c = UNSTREAM_STRING( &constant_bin[ 15090 ], 13, 0 );
    const_str_digest_3094a3153522c449dea0453cbf4eb75a = UNSTREAM_STRING( &constant_bin[ 2871 ], 13, 0 );
    const_str_digest_3394dfb307e06a954b858974260bf51d = UNSTREAM_STRING( &constant_bin[ 20160 ], 11, 0 );
    const_str_digest_391b5dc084c9caede4445b681a10e649 = UNSTREAM_STRING( &constant_bin[ 13857 ], 21, 0 );
    const_str_digest_3c2b5dd18916a4c86ef2a63bedc5a208 = UNSTREAM_STRING( &constant_bin[ 44416 ], 17, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 7134 ], 7, 0 );
    const_str_digest_4afb6ac3c5c448817b7c4b2a044b9750 = UNSTREAM_STRING( &constant_bin[ 44433 ], 15, 0 );
    const_str_digest_512956f71065199b4656d61ab6cfc176 = UNSTREAM_STRING( &constant_bin[ 14774 ], 9, 0 );
    const_str_digest_51cafa63df0dba009586a31c534cfea1 = UNSTREAM_STRING( &constant_bin[ 24621 ], 19, 0 );
    const_str_digest_597c21d905f294da7964cde2c14a8ed1 = UNSTREAM_STRING( &constant_bin[ 44448 ], 14, 0 );
    const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1 = UNSTREAM_STRING( &constant_bin[ 44462 ], 12, 0 );
    const_str_digest_634ebcb288116ec16a2922e44740c97d = UNSTREAM_STRING( &constant_bin[ 15016 ], 6, 0 );
    const_str_digest_6e1b9039a1198642c91d743e9550d006 = UNSTREAM_STRING( &constant_bin[ 25538 ], 14, 0 );
    const_str_digest_74ba315069266703540e145c62869e9e = UNSTREAM_STRING( &constant_bin[ 12022 ], 22, 0 );
    const_str_digest_7bb187c562694df4ba2daaaf74308c83 = UNSTREAM_STRING( &constant_bin[ 33696 ], 9, 0 );
    const_str_digest_7d12dd513df7295340b2dd17a294a989 = UNSTREAM_STRING( &constant_bin[ 14281 ], 14, 0 );
    const_str_digest_819ab0780a8b33f0b631ef3a18023e51 = UNSTREAM_STRING( &constant_bin[ 44474 ], 174, 0 );
    const_str_digest_86574d8f15512ec9e1567cf1229e45d5 = UNSTREAM_STRING( &constant_bin[ 19801 ], 9, 0 );
    const_str_digest_94699d22af3f3c8e06bb4fcc526cb18f = UNSTREAM_STRING( &constant_bin[ 2323 ], 12, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 44648 ], 46, 0 );
    const_str_digest_9aab03a7c38b52b642ae4b5d35cda670 = UNSTREAM_STRING( &constant_bin[ 20290 ], 8, 0 );
    const_str_digest_9de9d760fdabf779aba9714e2d037b5a = UNSTREAM_STRING( &constant_bin[ 1702 ], 12, 0 );
    const_str_digest_a9e53f924347f6fe3da0cfbd39c17c38 = UNSTREAM_STRING( &constant_bin[ 18755 ], 10, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 44694 ], 47, 0 );
    const_str_digest_ade26fea59a84e8b725866efbaa8d71b = UNSTREAM_STRING( &constant_bin[ 44741 ], 174, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 223 ], 2, 1 );
    const_str_digest_bf31fbca22bb3b1bbc45444e386bf3bf = UNSTREAM_STRING( &constant_bin[ 18867 ], 7, 0 );
    const_str_digest_c769738ed6d4e413a546d14f7794acc6 = UNSTREAM_STRING( &constant_bin[ 44915 ], 174, 0 );
    const_str_digest_c8a872f25f0ec1e4843cc7cb49a7c386 = UNSTREAM_STRING( &constant_bin[ 22340 ], 25, 0 );
    const_str_digest_cfcfe764e764d5cda77bfdc5151807d1 = UNSTREAM_STRING( &constant_bin[ 45089 ], 5, 0 );
    const_str_digest_d24e34aca5cb8b1f44f63ad311518436 = UNSTREAM_STRING( &constant_bin[ 18251 ], 8, 0 );
    const_str_digest_e16b0126d837ce7ad3b9f1fbd3704965 = UNSTREAM_STRING( &constant_bin[ 26831 ], 19, 0 );
    const_str_digest_e46e74d31c85f83e29b4c3ce2454e2c5 = UNSTREAM_STRING( &constant_bin[ 40562 ], 13, 0 );
    const_str_digest_ec911207fdb78e7ed2e951a8c5294e18 = UNSTREAM_STRING( &constant_bin[ 45094 ], 20, 0 );
    const_str_digest_f4e70d26441bda5de2c5387519e51cc6 = UNSTREAM_STRING( &constant_bin[ 45114 ], 37, 0 );
    const_tuple_str_plain_self_str_plain_aAlias_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aAlias_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aAlias_tuple, 1, const_str_plain_aAlias ); Py_INCREF( const_str_plain_aAlias );
    const_tuple_str_plain_self_str_plain_aValue_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aValue_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aValue_tuple, 1, const_str_plain_aValue ); Py_INCREF( const_str_plain_aValue );
    const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 0, (PyObject *)&PyFunction_Type ); Py_INCREF( (PyObject *)&PyFunction_Type );
    PyTuple_SET_ITEM( const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 1, (PyObject *)&PyCFunction_Type ); Py_INCREF( (PyObject *)&PyCFunction_Type );
    PyTuple_SET_ITEM( const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 2, (PyObject *)&PyMethod_Type ); Py_INCREF( (PyObject *)&PyMethod_Type );
    const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple = PyTuple_New( 10 );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 0, const_str_plain_Warning ); Py_INCREF( const_str_plain_Warning );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 1, const_str_plain_Error ); Py_INCREF( const_str_plain_Error );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 2, const_str_plain_InterfaceError ); Py_INCREF( const_str_plain_InterfaceError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 3, const_str_plain_DataError ); Py_INCREF( const_str_plain_DataError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 4, const_str_plain_DatabaseError ); Py_INCREF( const_str_plain_DatabaseError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 5, const_str_plain_OperationalError ); Py_INCREF( const_str_plain_OperationalError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 6, const_str_plain_IntegrityError ); Py_INCREF( const_str_plain_IntegrityError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 7, const_str_plain_InternalError ); Py_INCREF( const_str_plain_InternalError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 8, const_str_plain_NotSupportedError ); Py_INCREF( const_str_plain_NotSupportedError );
    PyTuple_SET_ITEM( const_tuple_cf8d71264ab2fa0bf4b6fd51a92c19f8_tuple, 9, const_str_plain_ProgrammingError ); Py_INCREF( const_str_plain_ProgrammingError );
    const_tuple_str_plain_self_str_plain_aParent_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aParent_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aParent_tuple, 1, const_str_plain_aParent ); Py_INCREF( const_str_plain_aParent );
    const_list_str_plain_instancemethod_str_plain_function_list = PyList_New( 2 );
    PyList_SET_ITEM( const_list_str_plain_instancemethod_str_plain_function_list, 0, const_str_plain_instancemethod ); Py_INCREF( const_str_plain_instancemethod );
    PyList_SET_ITEM( const_list_str_plain_instancemethod_str_plain_function_list, 1, const_str_plain_function ); Py_INCREF( const_str_plain_function );
    const_tuple_str_plain_self_str_plain_aKey_str_plain_aValue_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aKey_str_plain_aValue_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aKey_str_plain_aValue_tuple, 1, const_str_plain_aKey ); Py_INCREF( const_str_plain_aKey );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_aKey_str_plain_aValue_tuple, 2, const_str_plain_aValue ); Py_INCREF( const_str_plain_aValue );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_f4e70d26441bda5de2c5387519e51cc6
    );

    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_c8a872f25f0ec1e4843cc7cb49a7c386
    );

#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(2));

#if PYTHON_VERSION < 300
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyString_FromString("release"));
#else
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyUnicode_FromString("release"));
#endif
    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
